### ISSUE TITLE
Add CA key access to Patrick

### ISSUE THREAD

**Issue by rvolosatovs** [profianinc/infrastructure#107]
@puiterwijk please file a PR adding your age key to `.sops.yaml` for CA path regex and I will ensure the existing keys are encrypted for you as well.
Alternatively, feel free to simply regenerate the keys using the updated `.sops.yaml`. To do that:
1. Update `.sops.yaml` as outlined above
2. Run [`bootstrap`](https://github.com/profianinc/infrastructure/blob/996aa9b00bf5ff8e6abf487c1ecfaba4f176b158/overlays/tooling/bootstrap.nix#L2-L99), which will regenerate all CA cert/keys and Steward cert/keys
3. Redeploy Steward and Drawbridge instances (just `deploy -s` from the root is probably the simplest approach)

**Comment by puiterwijk** [comment]
I have for now generated and added a new key.
I'll try to cycle everything later when I have some more time.
