### ISSUE TITLE
Deploy the Enarx Kernel

### ISSUE THREAD

**Issue by npmccallum** [profianinc/infrastructure#12]
This will enable SGX and SNP support.

**Comment by npmccallum** [comment]
@rvolosatovs We'll need a 5.18 kernel as the base. Is that already set up?

**Comment by rvolosatovs** [comment]
> @rvolosatovs We'll need a 5.18 kernel as the base. Is that already set up?

On Equinix: yes

**Comment by rvolosatovs** [comment]
Done
