### ISSUE TITLE
Figure out why dependabot capitalizes bumps in Benefice

### ISSUE THREAD

**Issue by rvolosatovs** [profianinc/infrastructure#166]
Not sure where to file this

**Comment by dpal** [comment]
@bstrie will investigate and follow up an issue with Dependabot.

**Comment by rvolosatovs** [comment]
https://github.com/dependabot/dependabot-core/blob/37487d85e402e4edf8897972417c58516577392b/common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb#L45-L52

This is where the decision happens (thanks @haraldh for pointing out that this is an open-souce project)

I've made sure a PR is merged with correct title and commit message, let's see if it fixes the future PRs

**Comment by rvolosatovs** [comment]
It worked out https://github.com/profianinc/benefice/pull/240! :partying_face:
