### ISSUE TITLE
Switch to upstream `enarx` release

### ISSUE THREAD

**Issue by rvolosatovs** [profianinc/infrastructure#50]
Refs https://github.com/profianinc/infrastructure/commits/adafaf74bcacb8f8b05e40b90d414b72ba436ec5 introduced in https://github.com/profianinc/infrastructure/pull/48

Once https://github.com/enarx/enarx/issues/2053 is resolved, the URL should be updated https://github.com/profianinc/infrastructure/blob/dbbd8dcdd531148cb57c3efe06f07acd7a7abd2b/flake.nix#L30-L31

After that's done the following command should be executed:
```sh
$ nix flake lock --update-input enarx
```
(can be run via Docker/Podman if you don't have `nix` installed)

**Comment by platten** [comment]
Closed by #70
